{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_extra_width": 1,
	"caret_style": "blink",
	"color_scheme": "Packages/User/SublimeLinter/Agila Monokai Extended (SL).tmTheme",
	"create_window_at_startup": false,
	"fade_fold_buttons": false,
	"find_selected_text": true,
	"font_size": 15,
	"highlight_modified_tabs": true,
	"hot_exit": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_small_tab": false,
	"material_theme_tabs_autowidth": true,
	"material_theme_tabs_separator": true,
	"theme_agila_sidebar_font_small": true,
	"theme_agila_sidebar_light_icons": true,
	"theme_agila_compact_tab": true,
	"move_to_limit_on_up_down": true,
	"open_files_in_new_window": false,
	"overlay_scroll_bars": "enabled",
	"remember_open_files": true,
	"show_encoding": true,
	"show_full_path": true,
	"show_line_endings": true,
	"tab_size": 2,
	"theme": "Agila Monokai.sublime-theme",
	"translate_tabs_to_spaces": true,
	"ui_separator": true,
	"use_simple_full_screen": true
}
